const dropD = [
  {
    id: 0,
    name: "Electronics",
    path: "/electronics",
  },
  {
    id: 1,
    name: "Accessories",
    path: "/accessories",
  },
];

const homeCards = [
  {
    id: 0,
    heading: "Electronics",
    path: "/electronics",
    card1: "mobile",
    card2: "laptop",
    card3: "keyboards",
    description: "Get the Latest and the Best Deals Now",
    image1: "./utils/mobile.jpeg",
    image2: "./utils/laptops.jpeg",
    image3: "./utils/keyboards.jpeg",
  },
  // {
  //   id: 1,
  //   heading: "Accessories",
  //   path: "/accessories",
  //   card1: "Men",
  //   card2: "Women",
  //   card3: "Kids",
  //   description: "Get the Latest and the Best Deals Now",
  //   image1: "./utils/mobile.jpeg",
  //   image2: "./utils/laptops.jpeg",
  //   image3: "./utils/keyboards.jpeg",
  // },
];

const elecProd = [
  {
    id: 0,
    header: "Today's Combo Offer",
    offer: "x4",
    image: "./utils/Laptop1.webp",
    category: "laptop",
    model: "HP Notebook",
    MRP: "$1099",
    price: "$999",
    available: "6",
  },
  {
    id: 1,
    header: "Today's Combo Offer",
    offer: "x2",
    image: "./utils/Laptop2.webp",
    category: "laptop",
    model: "HP Envy",
    MRP: "$1199",
    price: "$1099",
    available: "7",
  },
  {
    id: 2,
    header: "Today's Combo Offer",
    offer: "x3",
    image: "./utils/Laptop3.webp",
    category: "laptop",
    model: "Toshiba B77",
    MRP: "$1399",
    price: "$1299",
    available: "5",
  },
  {
    id: 3,
    header: "Today's Combo Offer",
    offer: "x3",
    image: "./utils/Mobile1.jpg",
    category: "mobile",
    model: "Samsung Galaxy S23 Ultra 5G",
    MRP: "$1399",
    price: "$1299",
    available: "5",
  },
  {
    id: 4,
    header: "Today's Combo Offer",
    offer: "x3",
    image: "./utils/Mobile2.webp",
    category: "mobile",
    model: "One Plus 10 Pro 5G",
    MRP: "$1399",
    price: "$1299",
    available: "5",
  },
  {
    id: 5,
    header: "Today's Combo Offer",
    offer: "x3",
    image: "./utils/Mobile3.jpg",
    category: "mobile",
    model: "Google Pixel 7 Pro",
    MRP: "$1399",
    price: "$1299",
    available: "5",
  },
  {
    id: 6,
    header: "Today's Combo Offer",
    offer: "x3",
    image: "./utils/Laptop1.webp",
    category: "keyboard",
    model: "Toshiba B77",
    MRP: "$1399",
    price: "$1299",
    available: "5",
  },
  {
    id: 7,
    header: "Today's Combo Offer",
    offer: "x3",
    image: "./utils/Laptop2.webp",
    category: "keyboard",
    model: "Toshiba B77",
    MRP: "$1399",
    price: "$1299",
    available: "5",
  },
  {
    id: 8,
    header: "Today's Combo Offer",
    offer: "x3",
    image: "./utils/Laptop3.webp",
    category: "keyboard",
    model: "Toshiba B77",
    MRP: "$1399",
    price: "$1299",
    available: "5",
  },
];

export { dropD, elecProd, homeCards };
